#!/bin/bash

# Check if the PYFILE environment variable is set
if [[ -z "$PYFILE" ]]; then
  echo "The PYFILE environment variable is not set."
  exit 1
fi

# Compile the Python file
python3 -m py_compile "$PYFILE"

# Rename the compiled file to match the desired output filename
mv "${PYFILE}" "$PYFILE"c

echo "Compiling $PYFILE ..."
